In [9]:
import pandas as pd
import matplotlib as plt 
import seaborn as sns 
import numpy as np

In [10]:
red_wine= pd.read_csv('winequality-red.csv', sep=';')

In [11]:
red_wine.drop_duplicates()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
5               7.4             0.660         0.00             1.8      0.075   
...             ...               ...          ...             ...        ...   
1593            6.8             0.620         0.08             1.9      0.068   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
5                    13.0                  40.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1593                 28.0                  38.0  0.99651  3.42       0.82   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
5         9.4        5  
...       ...      ...  
1593      9.5        6  
1594     10.5        5  
1595     11.2        6  
1597     10.2        5  
1598     11.0        6  

[1359 rows x 12 columns]

## Adding label column


In [12]:
red_wine ['quality_label'] = red_wine['quality'].apply(
lambda value: 'low'
    if value <= 5 
    else 'medium' if value <= 7 
    else 'high')

red_wine['quality_label'] = pd.Categorical(red_wine['quality_label'],
categories=['low', 'medium', 'high'])

## Adding Wine Type

In [13]:
#red_wine['wine_type'] = 'Red'
#white_wine['wine_type'] = 'White'

In [14]:
red_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype   
---  ------                --------------  -----   
 0   fixed acidity         1599 non-null   float64 
 1   volatile acidity      1599 non-null   float64 
 2   citric acid           1599 non-null   float64 
 3   residual sugar        1599 non-null   float64 
 4   chlorides             1599 non-null   float64 
 5   free sulfur dioxide   1599 non-null   float64 
 6   total sulfur dioxide  1599 non-null   float64 
 7   density               1599 non-null   float64 
 8   pH                    1599 non-null   float64 
 9   sulphates             1599 non-null   float64 
 10  alcohol               1599 non-null   float64 
 11  quality               1599 non-null   int64   
 12  quality_label         1599 non-null   category
dtypes: category(1), float64(11), int64(1)
memory usage: 151.7 KB


In [15]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

## Encoding Label Encoding 

In [16]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
red_wine['quality_label'] = label_encoder.fit_transform(red_wine['quality_label'])

# Unique species after label encoding
print(red_wine['quality_label'].unique())

[1 2 0]


In [17]:
class_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))

print(class_mapping)

{'high': 0, 'low': 1, 'medium': 2}


In [18]:
red_wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  quality_label  
0      9.4        5              1  
1      9.8        5              1  
2      9.8        5              1  
3      9.8        6              2  
4      9.4        5              1

## Split

In [20]:
from sklearn.model_selection import train_test_split    

# Split data into features (X) and target (y)
# Ensure 'quality_label' is not included in the encoded columns if it's your target variable
X = red_wine.drop(['quality_label','quality'] , axis = 1)
y = red_wine['quality_label']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=52)

## Building Model

### Logistic Regression 

In [22]:
from sklearn.linear_model import LogisticRegression

# Initialize and fit the logistic regression model
lr_model_red = LogisticRegression(random_state=42)

#fit model
lr_model_red.fit(X_train, y_train)

# Make predictions on the test set
pred=lr_model_red.predict(X_test)

# import accuracy_score  metric
from sklearn.metrics import  accuracy_score 

# Calculate and print the accuracy score
acc = accuracy_score(y_test, pred)

print(acc)

0.69375


/Users/pierreloyal/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, pred)

array([[  0,   0,   3],
       [  0, 105,  42],
       [  0,  53, 117]])

In [25]:

from sklearn.metrics import precision_recall_fscore_support

# Calculate precision, recall, and F1-score
precision, recall, f1, _ = precision_recall_fscore_support(y_test, pred, average='weighted')

print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-Score: {f1}")

Precision: 0.6889614099859352
Recall: 0.69375
F1-Score: 0.6907262245704129


/Users/pierreloyal/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## IQR - Outliners 

In [26]:
# Calculate Q1, Q3, and IQR 

Q1 = red_wine['alcohol'].quantile(0.25)
Q3 = red_wine['alcohol'].quantile(0.75)
IQR = Q3 - Q1

# Define thresholds for outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

#identify outliers
outliers = red_wine[(red_wine['alcohol'] < lower_bound) | (red_wine['alcohol'] > upper_bound)]

# Remove
red_wine_filtered = red_wine[(red_wine['alcohol'] >= lower_bound) & (red_wine['alcohol'] <= upper_bound)]

print(f"Original dataset size: {len(red_wine)}")
print(f"Filtered dataset size: {len(red_wine_filtered)}")
print(f"Number of outliers removed: {len(outliers)}")

Original dataset size: 1599
Filtered dataset size: 1586
Number of outliers removed: 13


## Model LR WITHOUT outliners (red_wine_filtered)

In [27]:
from sklearn.model_selection import train_test_split    

# Split data into features (X) and target (y)
# Ensure 'quality_label' is not included in the encoded columns if it's your target variable
X = red_wine_filtered.drop(['quality_label','quality'] , axis = 1)
y = red_wine_filtered['quality_label']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=52)


from sklearn.linear_model import LogisticRegression

# Initialize and fit the logistic regression model
lr_model_red_filtered = LogisticRegression(random_state=42)

#fit model
lr_model_red_filtered.fit(X_train, y_train)

# Make predictions on the test set
pred=lr_model_red_filtered.predict(X_test)

# import accuracy_score  metric
from sklearn.metrics import  accuracy_score 

# Calculate and print the accuracy score
acc = accuracy_score(y_test, pred)

print(acc)

0.7484276729559748


/Users/pierreloyal/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## Model Random forrest 

In [28]:
# import Random Forest Classifier model
from  sklearn.ensemble import RandomForestClassifier

# Building model 
rf_model_red_filtered =  RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state=453)

# fit model 
rf_model_red_filtered.fit(X_train, y_train)

# Predict 
y_pred = rf_model_red_filtered.predict(X_test)

# Evaluate 
acc = accuracy_score(y_test, y_pred)
print(acc)

0.8176100628930818


### Confusion Matrix

In [29]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, pred)

array([[  0,   0,   1],
       [  0, 106,  32],
       [  0,  47, 132]])

### Precision, Recall, and F1-Score Calculation

In [30]:
from sklearn.metrics import precision_recall_fscore_support

# Calculate precision, recall, and F1-score
precision, recall, f1, _ = precision_recall_fscore_support(y_test, pred, average='weighted')

print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-Score: {f1}")

Precision: 0.7509680601800469
Recall: 0.7484276729559748
F1-Score: 0.7481389166587503


/Users/pierreloyal/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
